version: '3.8'
services:
  immunespace-mongodb:
    container_name: immunespace-mongodb
    image: mongo
    env_file:
      - .env
    restart: always
    volumes:
      - mongodb-data-container:/data/db
      - ./init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
    expose:
      - 27017
      - 27018
      - 27019
    networks:
      - immunespace_network

  fuse-provider-immunespace:
    container_name: fuse-provider-immunespace
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - immunespace-data-container:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - ${API_PORT}
    networks:
      - immunespace_network
    depends_on:
      - immunespace-mongodb

networks:
  immunespace_network:
    name: fuse
    external: true

volumes:
  mongodb-data-container:
    name: immunespace-mongo-db-data
  immunespace-data-container:
    name: immunespace-download-data

